#!/bin/sh

# Source GNUstep shell script to build environment...
if [ -e /usr/GNUstep/System/Library/Makefiles/GNUstep.sh ]
then
	. /usr/GNUstep/System/Library/Makefiles/GNUstep.sh
fi

# Set up LD_LIBRARY_PATH
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib

# Start the window manager...
wmaker
